-- =============================================================
-- CALENDARIO FISCAL SENIAT 2026 — Gaceta Oficial N° 43.273 (09/12/2025)
-- PA SNAT/2025/000091 (Sujetos Pasivos Especiales) y SNAT/2025/000093 (Pensiones)
-- Generado y verificado contra el escaneo de la gaceta. Idempotente.
-- =============================================================
create table if not exists public.calendario_fiscal (
  id bigserial primary key,
  fecha date not null,
  impuesto text not null,
  descripcion text not null,
  ambito text not null default 'especial',  -- 'especial' (solo sujetos pasivos especiales) | 'todos'
  terminales text not null                   -- últimos dígitos de RIF a los que aplica, ej '0' u '08'
);
create index if not exists idx_calfiscal_fecha on public.calendario_fiscal(fecha);
alter table public.calendario_fiscal enable row level security;
drop policy if exists calendario_lectura on public.calendario_fiscal;
create policy calendario_lectura on public.calendario_fiscal for select using (true); -- catálogo (como planes)

-- Recarga limpia del año 2026
delete from public.calendario_fiscal where fecha >= '2026-01-01' and fecha <= '2026-12-31';
insert into public.calendario_fiscal (fecha, impuesto, descripcion, ambito, terminales) values
('2026-01-28','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de enero (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','0'),
('2026-02-20','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de febrero (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','0'),
('2026-03-25','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de marzo (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','0'),
('2026-04-23','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de abril (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','0'),
('2026-05-20','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de mayo (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','0'),
('2026-06-29','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de junio (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','0'),
('2026-07-27','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de julio (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','0'),
('2026-08-31','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de agosto (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','0'),
('2026-09-29','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de septiembre (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','0'),
('2026-10-20','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de octubre (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','0'),
('2026-11-27','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de noviembre (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','0'),
('2026-12-16','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de diciembre (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','0'),
('2026-01-19','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de enero (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','1'),
('2026-02-23','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de febrero (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','1'),
('2026-03-20','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de marzo (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','1'),
('2026-04-27','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de abril (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','1'),
('2026-05-18','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de mayo (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','1'),
('2026-06-26','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de junio (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','1'),
('2026-07-21','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de julio (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','1'),
('2026-08-25','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de agosto (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','1'),
('2026-09-18','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de septiembre (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','1'),
('2026-10-28','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de octubre (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','1'),
('2026-11-26','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de noviembre (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','1'),
('2026-12-29','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de diciembre (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','1'),
('2026-01-21','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de enero (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','2'),
('2026-02-18','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de febrero (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','2'),
('2026-03-24','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de marzo (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','2'),
('2026-04-21','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de abril (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','2'),
('2026-05-29','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de mayo (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','2'),
('2026-06-16','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de junio (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','2'),
('2026-07-30','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de julio (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','2'),
('2026-08-24','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de agosto (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','2'),
('2026-09-24','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de septiembre (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','2'),
('2026-10-29','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de octubre (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','2'),
('2026-11-17','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de noviembre (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','2'),
('2026-12-21','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de diciembre (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','2'),
('2026-01-30','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de enero (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','3'),
('2026-02-18','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de febrero (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','3'),
('2026-03-23','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de marzo (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','3'),
('2026-04-30','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de abril (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','3'),
('2026-05-22','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de mayo (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','3'),
('2026-06-18','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de junio (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','3'),
('2026-07-23','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de julio (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','3'),
('2026-08-18','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de agosto (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','3'),
('2026-09-21','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de septiembre (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','3'),
('2026-10-23','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de octubre (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','3'),
('2026-11-23','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de noviembre (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','3'),
('2026-12-28','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de diciembre (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','3'),
('2026-01-23','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de enero (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','4'),
('2026-02-25','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de febrero (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','4'),
('2026-03-26','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de marzo (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','4'),
('2026-04-20','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de abril (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','4'),
('2026-05-21','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de mayo (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','4'),
('2026-06-19','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de junio (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','4'),
('2026-07-28','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de julio (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','4'),
('2026-08-19','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de agosto (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','4'),
('2026-09-30','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de septiembre (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','4'),
('2026-10-22','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de octubre (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','4'),
('2026-11-20','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de noviembre (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','4'),
('2026-12-22','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de diciembre (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','4'),
('2026-01-22','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de enero (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','5'),
('2026-02-27','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de febrero (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','5'),
('2026-03-30','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de marzo (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','5'),
('2026-04-22','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de abril (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','5'),
('2026-05-28','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de mayo (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','5'),
('2026-06-17','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de junio (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','5'),
('2026-07-22','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de julio (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','5'),
('2026-08-21','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de agosto (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','5'),
('2026-09-25','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de septiembre (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','5'),
('2026-10-30','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de octubre (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','5'),
('2026-11-18','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de noviembre (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','5'),
('2026-12-17','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de diciembre (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','5'),
('2026-01-20','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de enero (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','6'),
('2026-02-19','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de febrero (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','6'),
('2026-03-27','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de marzo (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','6'),
('2026-04-24','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de abril (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','6'),
('2026-05-19','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de mayo (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','6'),
('2026-06-30','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de junio (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','6'),
('2026-07-20','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de julio (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','6'),
('2026-08-28','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de agosto (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','6'),
('2026-09-28','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de septiembre (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','6'),
('2026-10-21','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de octubre (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','6'),
('2026-11-25','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de noviembre (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','6'),
('2026-12-18','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de diciembre (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','6'),
('2026-01-27','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de enero (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','7'),
('2026-02-24','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de febrero (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','7'),
('2026-03-18','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de marzo (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','7'),
('2026-04-17','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de abril (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','7'),
('2026-05-26','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de mayo (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','7'),
('2026-06-22','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de junio (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','7'),
('2026-07-31','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de julio (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','7'),
('2026-08-20','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de agosto (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','7'),
('2026-09-22','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de septiembre (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','7'),
('2026-10-27','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de octubre (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','7'),
('2026-11-19','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de noviembre (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','7'),
('2026-12-18','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de diciembre (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','7'),
('2026-01-26','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de enero (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','8'),
('2026-02-26','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de febrero (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','8'),
('2026-03-31','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de marzo (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','8'),
('2026-04-29','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de abril (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','8'),
('2026-05-27','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de mayo (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','8'),
('2026-06-23','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de junio (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','8'),
('2026-07-17','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de julio (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','8'),
('2026-08-26','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de agosto (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','8'),
('2026-09-17','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de septiembre (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','8'),
('2026-10-26','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de octubre (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','8'),
('2026-11-24','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de noviembre (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','8'),
('2026-12-30','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de diciembre (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','8'),
('2026-01-29','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de enero (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','9'),
('2026-02-27','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de febrero (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','9'),
('2026-03-17','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de marzo (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','9'),
('2026-04-28','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de abril (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','9'),
('2026-05-25','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de mayo (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','9'),
('2026-06-25','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de junio (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','9'),
('2026-07-29','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de julio (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','9'),
('2026-08-27','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de agosto (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','9'),
('2026-09-23','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de septiembre (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','9'),
('2026-10-19','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de octubre (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','9'),
('2026-11-30','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de noviembre (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','9'),
('2026-12-23','RET_IVA_1Q','Enterar retenciones de IVA practicadas del 01 al 15 de diciembre (+ declaración/anticipos IVA-ISLR 1ra quincena e IGTF)','especial','9'),
('2026-01-15','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de diciembre (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','0'),
('2026-02-09','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de enero (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','0'),
('2026-03-06','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de febrero (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','0'),
('2026-04-01','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de marzo (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','0'),
('2026-05-06','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de abril (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','0'),
('2026-06-12','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de mayo (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','0'),
('2026-07-08','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de junio (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','0'),
('2026-08-14','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de julio (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','0'),
('2026-09-14','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de agosto (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','0'),
('2026-10-05','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de septiembre (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','0'),
('2026-11-13','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de octubre (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','0'),
('2026-12-03','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de noviembre (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','0'),
('2026-01-06','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de diciembre (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','1'),
('2026-02-10','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de enero (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','1'),
('2026-03-03','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de febrero (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','1'),
('2026-04-14','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de marzo (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','1'),
('2026-05-04','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de abril (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','1'),
('2026-06-11','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de mayo (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','1'),
('2026-07-03','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de junio (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','1'),
('2026-08-13','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de julio (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','1'),
('2026-09-03','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de agosto (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','1'),
('2026-10-14','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de septiembre (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','1'),
('2026-11-12','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de octubre (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','1'),
('2026-12-15','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de noviembre (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','1'),
('2026-01-08','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de diciembre (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','2'),
('2026-02-05','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de enero (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','2'),
('2026-03-09','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de febrero (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','2'),
('2026-04-08','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de marzo (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','2'),
('2026-05-14','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de abril (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','2'),
('2026-06-03','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de mayo (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','2'),
('2026-07-14','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de junio (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','2'),
('2026-08-12','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de julio (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','2'),
('2026-09-10','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de agosto (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','2'),
('2026-10-15','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de septiembre (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','2'),
('2026-11-02','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de octubre (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','2'),
('2026-12-04','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de noviembre (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','2'),
('2026-01-16','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de diciembre (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','3'),
('2026-02-12','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de enero (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','3'),
('2026-03-04','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de febrero (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','3'),
('2026-04-16','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de marzo (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','3'),
('2026-05-07','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de abril (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','3'),
('2026-06-10','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de mayo (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','3'),
('2026-07-07','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de junio (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','3'),
('2026-08-05','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de julio (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','3'),
('2026-09-02','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de agosto (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','3'),
('2026-10-07','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de septiembre (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','3'),
('2026-11-09','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de octubre (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','3'),
('2026-12-11','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de noviembre (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','3'),
('2026-01-09','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de diciembre (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','4'),
('2026-02-02','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de enero (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','4'),
('2026-03-11','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de febrero (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','4'),
('2026-04-07','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de marzo (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','4'),
('2026-05-13','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de abril (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','4'),
('2026-06-02','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de mayo (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','4'),
('2026-07-10','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de junio (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','4'),
('2026-08-06','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de julio (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','4'),
('2026-09-09','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de agosto (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','4'),
('2026-10-06','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de septiembre (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','4'),
('2026-11-05','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de octubre (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','4'),
('2026-12-07','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de noviembre (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','4'),
('2026-01-05','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de diciembre (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','5'),
('2026-02-13','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de enero (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','5'),
('2026-03-12','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de febrero (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','5'),
('2026-04-09','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de marzo (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','5'),
('2026-05-15','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de abril (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','5'),
('2026-06-08','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de mayo (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','5'),
('2026-07-06','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de junio (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','5'),
('2026-08-03','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de julio (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','5'),
('2026-09-15','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de agosto (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','5'),
('2026-10-08','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de septiembre (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','5'),
('2026-11-04','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de octubre (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','5'),
('2026-12-10','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de noviembre (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','5'),
('2026-01-13','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de diciembre (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','6'),
('2026-02-04','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de enero (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','6'),
('2026-03-10','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de febrero (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','6'),
('2026-04-13','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de marzo (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','6'),
('2026-05-05','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de abril (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','6'),
('2026-06-15','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de mayo (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','6'),
('2026-07-09','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de junio (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','6'),
('2026-08-04','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de julio (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','6'),
('2026-09-11','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de agosto (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','6'),
('2026-10-02','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de septiembre (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','6'),
('2026-11-11','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de octubre (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','6'),
('2026-12-08','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de noviembre (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','6'),
('2026-01-12','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de diciembre (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','7'),
('2026-02-11','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de enero (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','7'),
('2026-03-02','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de febrero (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','7'),
('2026-04-06','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de marzo (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','7'),
('2026-05-11','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de abril (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','7'),
('2026-06-04','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de mayo (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','7'),
('2026-07-15','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de junio (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','7'),
('2026-08-10','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de julio (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','7'),
('2026-09-04','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de agosto (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','7'),
('2026-10-13','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de septiembre (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','7'),
('2026-11-03','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de octubre (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','7'),
('2026-12-02','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de noviembre (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','7'),
('2026-01-07','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de diciembre (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','8'),
('2026-02-03','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de enero (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','8'),
('2026-03-13','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de febrero (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','8'),
('2026-04-10','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de marzo (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','8'),
('2026-05-12','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de abril (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','8'),
('2026-06-05','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de mayo (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','8'),
('2026-07-02','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de junio (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','8'),
('2026-08-07','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de julio (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','8'),
('2026-09-08','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de agosto (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','8'),
('2026-10-09','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de septiembre (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','8'),
('2026-11-06','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de octubre (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','8'),
('2026-12-09','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de noviembre (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','8'),
('2026-01-14','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de diciembre (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','9'),
('2026-02-06','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de enero (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','9'),
('2026-03-05','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de febrero (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','9'),
('2026-04-15','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de marzo (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','9'),
('2026-05-08','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de abril (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','9'),
('2026-06-09','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de mayo (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','9'),
('2026-07-13','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de junio (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','9'),
('2026-08-11','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de julio (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','9'),
('2026-09-07','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de agosto (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','9'),
('2026-10-01','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de septiembre (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','9'),
('2026-11-10','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de octubre (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','9'),
('2026-12-14','RET_IVA_2Q','Enterar retenciones de IVA practicadas del 16 al último de noviembre (+ declaración/anticipos IVA-ISLR 2da quincena e IGTF)','especial','9'),
('2026-01-09','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (enero)','especial','14'),
('2026-02-10','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (febrero)','especial','14'),
('2026-03-11','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (marzo)','especial','14'),
('2026-04-14','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (abril)','especial','14'),
('2026-05-13','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (mayo)','especial','14'),
('2026-06-11','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (junio)','especial','14'),
('2026-07-10','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (julio)','especial','14'),
('2026-08-13','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (agosto)','especial','14'),
('2026-09-09','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (septiembre)','especial','14'),
('2026-10-14','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (octubre)','especial','14'),
('2026-11-12','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (noviembre)','especial','14'),
('2026-12-15','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (diciembre)','especial','14'),
('2026-01-08','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (enero)','especial','23'),
('2026-02-12','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (febrero)','especial','23'),
('2026-03-09','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (marzo)','especial','23'),
('2026-04-08','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (abril)','especial','23'),
('2026-05-14','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (mayo)','especial','23'),
('2026-06-10','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (junio)','especial','23'),
('2026-07-14','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (julio)','especial','23'),
('2026-08-12','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (agosto)','especial','23'),
('2026-09-10','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (septiembre)','especial','23'),
('2026-10-15','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (octubre)','especial','23'),
('2026-11-09','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (noviembre)','especial','23'),
('2026-12-11','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (diciembre)','especial','23'),
('2026-01-14','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (enero)','especial','59'),
('2026-02-13','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (febrero)','especial','59'),
('2026-03-12','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (marzo)','especial','59'),
('2026-04-09','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (abril)','especial','59'),
('2026-05-15','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (mayo)','especial','59'),
('2026-06-09','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (junio)','especial','59'),
('2026-07-13','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (julio)','especial','59'),
('2026-08-11','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (agosto)','especial','59'),
('2026-09-15','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (septiembre)','especial','59'),
('2026-10-08','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (octubre)','especial','59'),
('2026-11-10','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (noviembre)','especial','59'),
('2026-12-10','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (diciembre)','especial','59'),
('2026-01-13','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (enero)','especial','67'),
('2026-02-11','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (febrero)','especial','67'),
('2026-03-10','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (marzo)','especial','67'),
('2026-04-13','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (abril)','especial','67'),
('2026-05-11','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (mayo)','especial','67'),
('2026-06-15','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (junio)','especial','67'),
('2026-07-09','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (julio)','especial','67'),
('2026-08-10','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (agosto)','especial','67'),
('2026-09-11','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (septiembre)','especial','67'),
('2026-10-13','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (octubre)','especial','67'),
('2026-11-11','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (noviembre)','especial','67'),
('2026-12-08','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (diciembre)','especial','67'),
('2026-01-15','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (enero)','especial','08'),
('2026-02-09','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (febrero)','especial','08'),
('2026-03-13','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (marzo)','especial','08'),
('2026-04-10','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (abril)','especial','08'),
('2026-05-12','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (mayo)','especial','08'),
('2026-06-12','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (junio)','especial','08'),
('2026-07-08','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (julio)','especial','08'),
('2026-08-14','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (agosto)','especial','08'),
('2026-09-08','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (septiembre)','especial','08'),
('2026-10-09','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (octubre)','especial','08'),
('2026-11-13','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (noviembre)','especial','08'),
('2026-12-09','ISLR_ESTIMADA','Declaración y pago de porción — ISLR estimado (diciembre)','especial','08'),
('2026-01-09','RET_ISLR','Enterar retenciones de ISLR practicadas en diciembre','especial','14'),
('2026-02-10','RET_ISLR','Enterar retenciones de ISLR practicadas en enero','especial','14'),
('2026-03-11','RET_ISLR','Enterar retenciones de ISLR practicadas en febrero','especial','14'),
('2026-04-07','RET_ISLR','Enterar retenciones de ISLR practicadas en marzo','especial','14'),
('2026-05-13','RET_ISLR','Enterar retenciones de ISLR practicadas en abril','especial','14'),
('2026-06-11','RET_ISLR','Enterar retenciones de ISLR practicadas en mayo','especial','14'),
('2026-07-10','RET_ISLR','Enterar retenciones de ISLR practicadas en junio','especial','14'),
('2026-08-06','RET_ISLR','Enterar retenciones de ISLR practicadas en julio','especial','14'),
('2026-09-09','RET_ISLR','Enterar retenciones de ISLR practicadas en agosto','especial','14'),
('2026-10-06','RET_ISLR','Enterar retenciones de ISLR practicadas en septiembre','especial','14'),
('2026-11-05','RET_ISLR','Enterar retenciones de ISLR practicadas en octubre','especial','14'),
('2026-12-07','RET_ISLR','Enterar retenciones de ISLR practicadas en noviembre','especial','14'),
('2026-01-08','RET_ISLR','Enterar retenciones de ISLR practicadas en diciembre','especial','23'),
('2026-02-05','RET_ISLR','Enterar retenciones de ISLR practicadas en enero','especial','23'),
('2026-03-09','RET_ISLR','Enterar retenciones de ISLR practicadas en febrero','especial','23'),
('2026-04-08','RET_ISLR','Enterar retenciones de ISLR practicadas en marzo','especial','23'),
('2026-05-07','RET_ISLR','Enterar retenciones de ISLR practicadas en abril','especial','23'),
('2026-06-10','RET_ISLR','Enterar retenciones de ISLR practicadas en mayo','especial','23'),
('2026-07-07','RET_ISLR','Enterar retenciones de ISLR practicadas en junio','especial','23'),
('2026-08-12','RET_ISLR','Enterar retenciones de ISLR practicadas en julio','especial','23'),
('2026-09-10','RET_ISLR','Enterar retenciones de ISLR practicadas en agosto','especial','23'),
('2026-10-07','RET_ISLR','Enterar retenciones de ISLR practicadas en septiembre','especial','23'),
('2026-11-09','RET_ISLR','Enterar retenciones de ISLR practicadas en octubre','especial','23'),
('2026-12-04','RET_ISLR','Enterar retenciones de ISLR practicadas en noviembre','especial','23'),
('2026-01-14','RET_ISLR','Enterar retenciones de ISLR practicadas en diciembre','especial','59'),
('2026-02-06','RET_ISLR','Enterar retenciones de ISLR practicadas en enero','especial','59'),
('2026-03-05','RET_ISLR','Enterar retenciones de ISLR practicadas en febrero','especial','59'),
('2026-04-09','RET_ISLR','Enterar retenciones de ISLR practicadas en marzo','especial','59'),
('2026-05-08','RET_ISLR','Enterar retenciones de ISLR practicadas en abril','especial','59'),
('2026-06-09','RET_ISLR','Enterar retenciones de ISLR practicadas en mayo','especial','59'),
('2026-07-06','RET_ISLR','Enterar retenciones de ISLR practicadas en junio','especial','59'),
('2026-08-11','RET_ISLR','Enterar retenciones de ISLR practicadas en julio','especial','59'),
('2026-09-07','RET_ISLR','Enterar retenciones de ISLR practicadas en agosto','especial','59'),
('2026-10-08','RET_ISLR','Enterar retenciones de ISLR practicadas en septiembre','especial','59'),
('2026-11-10','RET_ISLR','Enterar retenciones de ISLR practicadas en octubre','especial','59'),
('2026-12-10','RET_ISLR','Enterar retenciones de ISLR practicadas en noviembre','especial','59'),
('2026-01-13','RET_ISLR','Enterar retenciones de ISLR practicadas en diciembre','especial','67'),
('2026-02-11','RET_ISLR','Enterar retenciones de ISLR practicadas en enero','especial','67'),
('2026-03-10','RET_ISLR','Enterar retenciones de ISLR practicadas en febrero','especial','67'),
('2026-04-06','RET_ISLR','Enterar retenciones de ISLR practicadas en marzo','especial','67'),
('2026-05-11','RET_ISLR','Enterar retenciones de ISLR practicadas en abril','especial','67'),
('2026-06-04','RET_ISLR','Enterar retenciones de ISLR practicadas en mayo','especial','67'),
('2026-07-09','RET_ISLR','Enterar retenciones de ISLR practicadas en junio','especial','67'),
('2026-08-10','RET_ISLR','Enterar retenciones de ISLR practicadas en julio','especial','67'),
('2026-09-04','RET_ISLR','Enterar retenciones de ISLR practicadas en agosto','especial','67'),
('2026-10-13','RET_ISLR','Enterar retenciones de ISLR practicadas en septiembre','especial','67'),
('2026-11-11','RET_ISLR','Enterar retenciones de ISLR practicadas en octubre','especial','67'),
('2026-12-08','RET_ISLR','Enterar retenciones de ISLR practicadas en noviembre','especial','67'),
('2026-01-15','RET_ISLR','Enterar retenciones de ISLR practicadas en diciembre','especial','08'),
('2026-02-09','RET_ISLR','Enterar retenciones de ISLR practicadas en enero','especial','08'),
('2026-03-06','RET_ISLR','Enterar retenciones de ISLR practicadas en febrero','especial','08'),
('2026-04-10','RET_ISLR','Enterar retenciones de ISLR practicadas en marzo','especial','08'),
('2026-05-12','RET_ISLR','Enterar retenciones de ISLR practicadas en abril','especial','08'),
('2026-06-05','RET_ISLR','Enterar retenciones de ISLR practicadas en mayo','especial','08'),
('2026-07-08','RET_ISLR','Enterar retenciones de ISLR practicadas en junio','especial','08'),
('2026-08-07','RET_ISLR','Enterar retenciones de ISLR practicadas en julio','especial','08'),
('2026-09-08','RET_ISLR','Enterar retenciones de ISLR practicadas en agosto','especial','08'),
('2026-10-09','RET_ISLR','Enterar retenciones de ISLR practicadas en septiembre','especial','08'),
('2026-11-06','RET_ISLR','Enterar retenciones de ISLR practicadas en octubre','especial','08'),
('2026-12-09','RET_ISLR','Enterar retenciones de ISLR practicadas en noviembre','especial','08'),
('2026-03-11','ISLR_ANUAL','Autoliquidación anual de ISLR — ejercicio 01/01/2025 al 31/12/2025','especial','14'),
('2026-01-30','ISLR_ANUAL','Autoliquidación anual de ISLR — ejercicio 01/01/2025 al 31/12/2025','especial','23'),
('2026-02-27','ISLR_ANUAL','Autoliquidación anual de ISLR — ejercicio 01/01/2025 al 31/12/2025','especial','59'),
('2026-03-16','ISLR_ANUAL','Autoliquidación anual de ISLR — ejercicio 01/01/2025 al 31/12/2025','especial','67'),
('2026-03-06','ISLR_ANUAL','Autoliquidación anual de ISLR — ejercicio 01/01/2025 al 31/12/2025','especial','08'),
('2026-10-14','IGP','Impuesto a los Grandes Patrimonios — declaración y pago (1er lapso)','especial','14'),
('2026-11-12','IGP','Impuesto a los Grandes Patrimonios — declaración y pago (2do lapso)','especial','14'),
('2026-10-15','IGP','Impuesto a los Grandes Patrimonios — declaración y pago (1er lapso)','especial','23'),
('2026-11-09','IGP','Impuesto a los Grandes Patrimonios — declaración y pago (2do lapso)','especial','23'),
('2026-10-08','IGP','Impuesto a los Grandes Patrimonios — declaración y pago (1er lapso)','especial','59'),
('2026-11-10','IGP','Impuesto a los Grandes Patrimonios — declaración y pago (2do lapso)','especial','59'),
('2026-10-13','IGP','Impuesto a los Grandes Patrimonios — declaración y pago (1er lapso)','especial','67'),
('2026-11-11','IGP','Impuesto a los Grandes Patrimonios — declaración y pago (2do lapso)','especial','67'),
('2026-10-09','IGP','Impuesto a los Grandes Patrimonios — declaración y pago (1er lapso)','especial','08'),
('2026-11-13','IGP','Impuesto a los Grandes Patrimonios — declaración y pago (2do lapso)','especial','08'),
('2026-01-28','DPP','Contribución Protección de Pensiones — pagos de diciembre','todos','0'),
('2026-02-20','DPP','Contribución Protección de Pensiones — pagos de enero','todos','0'),
('2026-03-25','DPP','Contribución Protección de Pensiones — pagos de febrero','todos','0'),
('2026-04-23','DPP','Contribución Protección de Pensiones — pagos de marzo','todos','0'),
('2026-05-20','DPP','Contribución Protección de Pensiones — pagos de abril','todos','0'),
('2026-06-29','DPP','Contribución Protección de Pensiones — pagos de mayo','todos','0'),
('2026-07-27','DPP','Contribución Protección de Pensiones — pagos de junio','todos','0'),
('2026-08-17','DPP','Contribución Protección de Pensiones — pagos de julio','todos','0'),
('2026-09-29','DPP','Contribución Protección de Pensiones — pagos de agosto','todos','0'),
('2026-10-20','DPP','Contribución Protección de Pensiones — pagos de septiembre','todos','0'),
('2026-11-27','DPP','Contribución Protección de Pensiones — pagos de octubre','todos','0'),
('2026-12-16','DPP','Contribución Protección de Pensiones — pagos de noviembre','todos','0'),
('2026-01-19','DPP','Contribución Protección de Pensiones — pagos de diciembre','todos','1'),
('2026-02-23','DPP','Contribución Protección de Pensiones — pagos de enero','todos','1'),
('2026-03-20','DPP','Contribución Protección de Pensiones — pagos de febrero','todos','1'),
('2026-04-27','DPP','Contribución Protección de Pensiones — pagos de marzo','todos','1'),
('2026-05-18','DPP','Contribución Protección de Pensiones — pagos de abril','todos','1'),
('2026-06-26','DPP','Contribución Protección de Pensiones — pagos de mayo','todos','1'),
('2026-07-21','DPP','Contribución Protección de Pensiones — pagos de junio','todos','1'),
('2026-08-25','DPP','Contribución Protección de Pensiones — pagos de julio','todos','1'),
('2026-09-18','DPP','Contribución Protección de Pensiones — pagos de agosto','todos','1'),
('2026-10-28','DPP','Contribución Protección de Pensiones — pagos de septiembre','todos','1'),
('2026-11-26','DPP','Contribución Protección de Pensiones — pagos de octubre','todos','1'),
('2026-12-29','DPP','Contribución Protección de Pensiones — pagos de noviembre','todos','1'),
('2026-01-21','DPP','Contribución Protección de Pensiones — pagos de diciembre','todos','2'),
('2026-02-18','DPP','Contribución Protección de Pensiones — pagos de enero','todos','2'),
('2026-03-24','DPP','Contribución Protección de Pensiones — pagos de febrero','todos','2'),
('2026-04-21','DPP','Contribución Protección de Pensiones — pagos de marzo','todos','2'),
('2026-05-29','DPP','Contribución Protección de Pensiones — pagos de abril','todos','2'),
('2026-06-16','DPP','Contribución Protección de Pensiones — pagos de mayo','todos','2'),
('2026-07-30','DPP','Contribución Protección de Pensiones — pagos de junio','todos','2'),
('2026-08-24','DPP','Contribución Protección de Pensiones — pagos de julio','todos','2'),
('2026-09-24','DPP','Contribución Protección de Pensiones — pagos de agosto','todos','2'),
('2026-10-29','DPP','Contribución Protección de Pensiones — pagos de septiembre','todos','2'),
('2026-11-17','DPP','Contribución Protección de Pensiones — pagos de octubre','todos','2'),
('2026-12-21','DPP','Contribución Protección de Pensiones — pagos de noviembre','todos','2'),
('2026-01-30','DPP','Contribución Protección de Pensiones — pagos de diciembre','todos','3'),
('2026-02-12','DPP','Contribución Protección de Pensiones — pagos de enero','todos','3'),
('2026-03-23','DPP','Contribución Protección de Pensiones — pagos de febrero','todos','3'),
('2026-04-30','DPP','Contribución Protección de Pensiones — pagos de marzo','todos','3'),
('2026-05-22','DPP','Contribución Protección de Pensiones — pagos de abril','todos','3'),
('2026-06-18','DPP','Contribución Protección de Pensiones — pagos de mayo','todos','3'),
('2026-07-23','DPP','Contribución Protección de Pensiones — pagos de junio','todos','3'),
('2026-08-18','DPP','Contribución Protección de Pensiones — pagos de julio','todos','3'),
('2026-09-21','DPP','Contribución Protección de Pensiones — pagos de agosto','todos','3'),
('2026-10-23','DPP','Contribución Protección de Pensiones — pagos de septiembre','todos','3'),
('2026-11-23','DPP','Contribución Protección de Pensiones — pagos de octubre','todos','3'),
('2026-12-28','DPP','Contribución Protección de Pensiones — pagos de noviembre','todos','3'),
('2026-01-23','DPP','Contribución Protección de Pensiones — pagos de diciembre','todos','4'),
('2026-02-25','DPP','Contribución Protección de Pensiones — pagos de enero','todos','4'),
('2026-03-26','DPP','Contribución Protección de Pensiones — pagos de febrero','todos','4'),
('2026-04-20','DPP','Contribución Protección de Pensiones — pagos de marzo','todos','4'),
('2026-05-21','DPP','Contribución Protección de Pensiones — pagos de abril','todos','4'),
('2026-06-19','DPP','Contribución Protección de Pensiones — pagos de mayo','todos','4'),
('2026-07-28','DPP','Contribución Protección de Pensiones — pagos de junio','todos','4'),
('2026-08-19','DPP','Contribución Protección de Pensiones — pagos de julio','todos','4'),
('2026-09-16','DPP','Contribución Protección de Pensiones — pagos de agosto','todos','4'),
('2026-10-22','DPP','Contribución Protección de Pensiones — pagos de septiembre','todos','4'),
('2026-11-20','DPP','Contribución Protección de Pensiones — pagos de octubre','todos','4'),
('2026-12-22','DPP','Contribución Protección de Pensiones — pagos de noviembre','todos','4'),
('2026-01-22','DPP','Contribución Protección de Pensiones — pagos de diciembre','todos','5'),
('2026-02-13','DPP','Contribución Protección de Pensiones — pagos de enero','todos','5'),
('2026-03-30','DPP','Contribución Protección de Pensiones — pagos de febrero','todos','5'),
('2026-04-22','DPP','Contribución Protección de Pensiones — pagos de marzo','todos','5'),
('2026-05-28','DPP','Contribución Protección de Pensiones — pagos de abril','todos','5'),
('2026-06-17','DPP','Contribución Protección de Pensiones — pagos de mayo','todos','5'),
('2026-07-22','DPP','Contribución Protección de Pensiones — pagos de junio','todos','5'),
('2026-08-21','DPP','Contribución Protección de Pensiones — pagos de julio','todos','5'),
('2026-09-25','DPP','Contribución Protección de Pensiones — pagos de agosto','todos','5'),
('2026-10-16','DPP','Contribución Protección de Pensiones — pagos de septiembre','todos','5'),
('2026-11-18','DPP','Contribución Protección de Pensiones — pagos de octubre','todos','5'),
('2026-12-17','DPP','Contribución Protección de Pensiones — pagos de noviembre','todos','5'),
('2026-01-20','DPP','Contribución Protección de Pensiones — pagos de diciembre','todos','6'),
('2026-02-19','DPP','Contribución Protección de Pensiones — pagos de enero','todos','6'),
('2026-03-27','DPP','Contribución Protección de Pensiones — pagos de febrero','todos','6'),
('2026-04-24','DPP','Contribución Protección de Pensiones — pagos de marzo','todos','6'),
('2026-05-19','DPP','Contribución Protección de Pensiones — pagos de abril','todos','6'),
('2026-06-30','DPP','Contribución Protección de Pensiones — pagos de mayo','todos','6'),
('2026-07-20','DPP','Contribución Protección de Pensiones — pagos de junio','todos','6'),
('2026-08-28','DPP','Contribución Protección de Pensiones — pagos de julio','todos','6'),
('2026-09-28','DPP','Contribución Protección de Pensiones — pagos de agosto','todos','6'),
('2026-10-21','DPP','Contribución Protección de Pensiones — pagos de septiembre','todos','6'),
('2026-11-25','DPP','Contribución Protección de Pensiones — pagos de octubre','todos','6'),
('2026-12-15','DPP','Contribución Protección de Pensiones — pagos de noviembre','todos','6'),
('2026-01-27','DPP','Contribución Protección de Pensiones — pagos de diciembre','todos','7'),
('2026-02-24','DPP','Contribución Protección de Pensiones — pagos de enero','todos','7'),
('2026-03-18','DPP','Contribución Protección de Pensiones — pagos de febrero','todos','7'),
('2026-04-17','DPP','Contribución Protección de Pensiones — pagos de marzo','todos','7'),
('2026-05-26','DPP','Contribución Protección de Pensiones — pagos de abril','todos','7'),
('2026-06-22','DPP','Contribución Protección de Pensiones — pagos de mayo','todos','7'),
('2026-07-16','DPP','Contribución Protección de Pensiones — pagos de junio','todos','7'),
('2026-08-20','DPP','Contribución Protección de Pensiones — pagos de julio','todos','7'),
('2026-09-22','DPP','Contribución Protección de Pensiones — pagos de agosto','todos','7'),
('2026-10-27','DPP','Contribución Protección de Pensiones — pagos de septiembre','todos','7'),
('2026-11-19','DPP','Contribución Protección de Pensiones — pagos de octubre','todos','7'),
('2026-12-18','DPP','Contribución Protección de Pensiones — pagos de noviembre','todos','7'),
('2026-01-26','DPP','Contribución Protección de Pensiones — pagos de diciembre','todos','8'),
('2026-02-26','DPP','Contribución Protección de Pensiones — pagos de enero','todos','8'),
('2026-03-16','DPP','Contribución Protección de Pensiones — pagos de febrero','todos','8'),
('2026-04-29','DPP','Contribución Protección de Pensiones — pagos de marzo','todos','8'),
('2026-05-27','DPP','Contribución Protección de Pensiones — pagos de abril','todos','8'),
('2026-06-23','DPP','Contribución Protección de Pensiones — pagos de mayo','todos','8'),
('2026-07-17','DPP','Contribución Protección de Pensiones — pagos de junio','todos','8'),
('2026-08-26','DPP','Contribución Protección de Pensiones — pagos de julio','todos','8'),
('2026-09-17','DPP','Contribución Protección de Pensiones — pagos de agosto','todos','8'),
('2026-10-26','DPP','Contribución Protección de Pensiones — pagos de septiembre','todos','8'),
('2026-11-24','DPP','Contribución Protección de Pensiones — pagos de octubre','todos','8'),
('2026-12-30','DPP','Contribución Protección de Pensiones — pagos de noviembre','todos','8'),
('2026-01-29','DPP','Contribución Protección de Pensiones — pagos de diciembre','todos','9'),
('2026-02-27','DPP','Contribución Protección de Pensiones — pagos de enero','todos','9'),
('2026-03-17','DPP','Contribución Protección de Pensiones — pagos de febrero','todos','9'),
('2026-04-28','DPP','Contribución Protección de Pensiones — pagos de marzo','todos','9'),
('2026-05-25','DPP','Contribución Protección de Pensiones — pagos de abril','todos','9'),
('2026-06-25','DPP','Contribución Protección de Pensiones — pagos de mayo','todos','9'),
('2026-07-29','DPP','Contribución Protección de Pensiones — pagos de junio','todos','9'),
('2026-08-27','DPP','Contribución Protección de Pensiones — pagos de julio','todos','9'),
('2026-09-23','DPP','Contribución Protección de Pensiones — pagos de agosto','todos','9'),
('2026-10-19','DPP','Contribución Protección de Pensiones — pagos de septiembre','todos','9'),
('2026-11-16','DPP','Contribución Protección de Pensiones — pagos de octubre','todos','9'),
('2026-12-23','DPP','Contribución Protección de Pensiones — pagos de noviembre','todos','9');

select impuesto, count(*) as fechas from public.calendario_fiscal group by impuesto order by impuesto;
